// message catalog
var model_all = "test";

var message = {
	"KOR": {
		model: model_all,
		docuInfo: "문서 정보",
		search: "Search",
		keyword: "검색어 입력",
		result: "검색 결과가 없습니다.",
		result_toc: "목차 검색",
		result_body: "내용 검색",
		search_short: "검색어가 너무 짧습니다.",
		search_more: "더보기",
		search_less: "숨기기",
		close: "닫기",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"ENG": {
		model: model_all,
		docuInfo: "About This Documentation",
		search: "Search",
		keyword: "Enter search term",
		result: "No results were found for your search.",
		result_toc: "Table of contents",
		result_body: "Contents",
		search_short: "Search term is too short",
		search_more: "More",
		search_less: "Hide",
		close: "Close",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"CHN": {
		model: model_all,
		docuInfo: "文档信息",
		search: "Search",
		keyword: "输入搜索词",
		result: "找不到与您的搜索相关的结果。",
		result_toc: "目录检索",
		result_body: "内容搜寻",
		search_short: "您的搜索词太短。",
		search_more: "更多",
		search_less: "隐藏",
		close: "关",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"JPN": {
		model: model_all,
		docuInfo: "文書情報",
		search: "探す",
		keyword: "検索キーワードを入力",
		result: "検索結果がありません。",
		result_toc: "目次",
		result_body: "内容",
		search_short: "検索語が短すぎます",
		search_more: "もっと",
		search_less: "隠す",
		close: "閉じる",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"TWN": {
		model: model_all,
		docuInfo: "文件資訊",
		search: "搜索",
		keyword: "輸入搜索詞",
		result: "找不到與您的搜索相關的結果。",
		result_toc: "目錄",
		result_body: "內容",
		search_short: "搜索詞太短",
		search_more: "更多",
		search_less: "隱藏",
		close: "關",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"VNM": {
		model: model_all,
		docuInfo: "Về tài liệu này",
		search: "Tìm kiếm",
		keyword: "Nhập cụm từ tìm kiếm",
		result: "Không có kết quả nào được tìm thấy cho tìm kiếm của bạn.",
		result_toc: "Mục lục",
		result_body: "Nội dung",
		search_short: "Cụm từ tìm kiếm quá ngắn",
		search_more: "Hơn",
		search_less: "Ẩn giấu",
		close: "Đóng",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"DEU": {
		model: model_all,
		docuInfo: "Über dieses Dokument",
		search: "Suche",
		keyword: "Suchbegriff eingeben",
		result: "Es wurden keine Ergebnisse für deine Suche gefunden.",
		result_toc: "Inhaltsverzeichnis",
		result_body: "Inhalt",
		search_short: "Suchbegriff ist zu kurz",
		search_more: "Mehr",
		search_less: "Ausblenden",
		close: "Schließen",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"HUN": {
		model: model_all,
		docuInfo: "A dokumentumról",
		search: "Keresés",
		keyword: "Írja be a keresési kifejezést",
		result: "Nem található találat a keresésre.",
		result_toc: "Tartalomjegyzék",
		result_body: "Tartalom",
		search_short: "A keresési kifejezés túl rövid",
		search_more: "Több",
		search_less: "Elrejt",
		close: "Bezárás",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"ROM": {
		model: model_all,
		docuInfo: "Despre acest document",
		search: "Căutare",
		keyword: "Introduceți termenul de căutare",
		result: "Nu s-au găsit rezultate pentru căutarea dvs.",
		result_toc: "Cuprins",
		result_body: "Cuprins",
		search_short: "Termenul de căutare este prea scurt",
		search_more: "Mai Mult",
		search_less: "Ascunde",
		close: "Închide",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"FRA": {
		model: model_all,
		docuInfo: "À propos de ce document",
		search: "Chercher",
		keyword: "Entrez le terme de recherche",
		result: "Aucun résultat n'a été trouvé pour votre recherche.",
		result_toc: "Table des matières",
		result_body: "Contenu",
		search_short: "Le terme de recherche est trop court",
		search_more: "Plus",
		search_less: "Cacher",
		close: "Fermer",
		language_header: "LANGUAGE",
		error_page: "error"
	},
	"ESP": {
		model: model_all,
		docuInfo: "Acerca de este documento",
		search: "Buscar",
		keyword: "Ingrese término de búsqueda",
		result: "No se encontraron resultados para tu búsqueda.",
		result_toc: "Tabla de contenido",
		result_body: "Contenido",
		search_short: "El término de búsqueda es demasiado corto",
		search_more: "Más",
		search_less: "Esconder",
		close: "Cerca",
		language_header: "LANGUAGE",
		error_page: "error"
	}
};