var message = {
    "English": {
        title: "Help",
        search: "Search",
        home: "Home",
        list: "List",
        settings: "Settings",
        font_tit: "Font size",
        line_tit: "Line spacing",
        view_toc3: "Key Features",
        toc_bottom: "Some content on your device may differ or change without notice.",
        keyword: "Enter search keyword",
        recent_key: "Recent keywords",
        result: "No results found.",
        expand: "Expand",
        collapse: "Collapse",
        result_toc: "Table of contents",
        search_short: "Keyword is too short.",
        search_more: "More",
        search_less: "Less",
        bookmark: "Bookmark pages that you frequently view to get quick access.<br />To bookmark a page, tap <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> at the bottom of the screen. The page will be added to your bookmarks list.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
        close: "Close",
        bookmark_tit: "Bookmarks",
        basic_tit: "Basics",
        application_tit: "Applications",
        setting_tit: "Settings",
        recom_tit: "Recommended",
        privacy_tit: "Privacy and safety",
        connect_tit: "Connectivity",
        setting_tit1: " ",
        setting_tit2: " ",
        setting_tit3: " ",
        setting_tit4: " ",
        intro: "Introduction",
        bookmark_over: "You can add up to 20 pages to the bookmarks list.",
        selectbox_choose: "Please choose",
        welcome: "Welcome",
        find_err: "No results found.<br/>Tap Close to go to the main page.",
        app_err: "The requested page could not be found.<br/>Tap Close to go to the main page.",
        fb_title: "Was this content helpful?",
        fb_yes: "YES",
        fb_no: "NO",
        fb_submit: "SUBMIT"
    },
    "Spanish_LA": {
        title: "Ayuda",
        search: "Buscar",
        home: "Inicio",
        list: "Lista",
        settings: "Config.",
        font_tit: "Tamaño de fuente",
        line_tit: "Espaciado entre líneas",
        view_toc3: "Funciones básicas",
        toc_bottom: "Ciertos contenidos del dispositivo podrían ser diferentes o cambiar sin previo aviso.",
        keyword: "Ingresar palabra clave de búsqueda",
        recent_key: "Palabras clave recientes",
        result: "No se encontraron resultados.",
        result_toc: "Índice",
        search_short: "La palabra clave es demasiado corta.",
        search_more: "Más",
        search_less: "Menos",
        bookmark: "Marque páginas que visita frecuentemente para acceder a ellas rápidamente.<br />Para marcar una página, pulse <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> en la parte inferior de la pantalla. La página se añadirá a la lista de marcadores.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
        close: "Cerrar",
        bookmark_tit: "Marcadores",
        basic_tit: "Nociones básicas",
        application_tit: "Aplicaciones",
        setting_tit: "Config.",
        recom_tit: "Recomendado",
        privacy_tit: "Privacidad y seguridad",
        connect_tit: "Conectividad",
        setting_tit1: "Conexiones",
        setting_tit2: "Dispositivo",
        setting_tit3: "Personal",
        setting_tit4: "Sistema",
        intro: "Introducción",
        bookmark_over: "Podrá añadir hasta 20 páginas a la lista de marcadores.",
        selectbox_choose: "Por favor elija",
        welcome: "Bienvenido",
        find_err: "No se encontraron resultados.<br />Pulse Cerrar para ir a la página principal.",
        app_err: "No se encontró la página solicitada.<br />Pulse Cerrar para ir a la página principal.",
        fb_title: "¿Le resultó útil este contenido?",
        fb_yes: "SÍ",
        fb_no: "NO",
        fb_submit: "ENVIAR"
    }
};